/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms.project;

/**
 *
 * @author jeevitha
 */
public class Customer_page extends javax.swing.JFrame {

    /**
     * Creates new form Customer_page
     */
    public Customer_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cart = new javax.swing.JButton();
        contact = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        feedback = new javax.swing.JButton();
        clothing = new javax.swing.JButton();
        bags = new javax.swing.JButton();
        footwear = new javax.swing.JButton();
        electronic = new javax.swing.JButton();
        books = new javax.swing.JButton();
        beauty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/project/banner-shop.gif"))); // NOI18N
        jLabel1.setText("jLabel1");

        cart.setBackground(new java.awt.Color(255, 255, 255));
        cart.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        cart.setForeground(new java.awt.Color(0, 0, 102));
        cart.setText("cart");
        cart.setBorder(null);
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });

        contact.setBackground(new java.awt.Color(255, 255, 255));
        contact.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        contact.setForeground(new java.awt.Color(0, 0, 102));
        contact.setText("contact us");
        contact.setBorder(null);
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 0, 102));
        logout.setText("logout");
        logout.setBorder(null);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        feedback.setBackground(new java.awt.Color(255, 255, 255));
        feedback.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        feedback.setForeground(new java.awt.Color(0, 0, 102));
        feedback.setText("feedback");
        feedback.setBorder(null);
        feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackActionPerformed(evt);
            }
        });

        clothing.setBackground(new java.awt.Color(255, 153, 255));
        clothing.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        clothing.setForeground(new java.awt.Color(255, 255, 255));
        clothing.setText("Clothing");
        clothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothingActionPerformed(evt);
            }
        });

        bags.setBackground(new java.awt.Color(204, 153, 255));
        bags.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bags.setForeground(new java.awt.Color(255, 255, 255));
        bags.setText("Books");
        bags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagsActionPerformed(evt);
            }
        });

        footwear.setBackground(new java.awt.Color(102, 102, 255));
        footwear.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        footwear.setForeground(new java.awt.Color(255, 255, 255));
        footwear.setText("Footwear");
        footwear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                footwearActionPerformed(evt);
            }
        });

        electronic.setBackground(new java.awt.Color(255, 204, 102));
        electronic.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        electronic.setForeground(new java.awt.Color(255, 255, 255));
        electronic.setText("Electronics");
        electronic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electronicActionPerformed(evt);
            }
        });

        books.setBackground(new java.awt.Color(153, 255, 204));
        books.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        books.setForeground(new java.awt.Color(255, 255, 255));
        books.setText("Bags");
        books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksActionPerformed(evt);
            }
        });

        beauty.setBackground(new java.awt.Color(255, 51, 51));
        beauty.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        beauty.setForeground(new java.awt.Color(255, 255, 255));
        beauty.setText("Beauty");
        beauty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beautyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(705, Short.MAX_VALUE)
                        .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clothing, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beauty, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(books, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(bags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(footwear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(electronic, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(footwear, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(books, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clothing, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(electronic, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bags, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beauty, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
        new cart_page().setVisible(true);
    
    }//GEN-LAST:event_cartActionPerformed

    private void feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
        new Feedback_form().setVisible(true);
    }//GEN-LAST:event_feedbackActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
               this.setVisible(false);
        new Login_form().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void beautyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beautyActionPerformed
        // TODO add your handling code here:
                      this.setVisible(false);
        new beauty_page().setVisible(true);
        
    }//GEN-LAST:event_beautyActionPerformed

    private void clothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothingActionPerformed
                      this.setVisible(false);
        new Clothing_page().setVisible(true);
    }//GEN-LAST:event_clothingActionPerformed

    private void bagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagsActionPerformed
                 this.setVisible(false);
        new books_page().setVisible(true);
    }//GEN-LAST:event_bagsActionPerformed

    private void footwearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footwearActionPerformed
        // TODO add your handling code here:
                      this.setVisible(false);
        new footwear_page().setVisible(true);
    }//GEN-LAST:event_footwearActionPerformed

    private void booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksActionPerformed
                      this.setVisible(false);
        new bags_page().setVisible(true);
    }//GEN-LAST:event_booksActionPerformed

    private void electronicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electronicActionPerformed
        // TODO add your handling code here:
                      this.setVisible(false);
        new electronics_page().setVisible(true);
    }//GEN-LAST:event_electronicActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
                      this.setVisible(false);
        new Contact_form().setVisible(true);
    }//GEN-LAST:event_contactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bags;
    private javax.swing.JButton beauty;
    private javax.swing.JButton books;
    private javax.swing.JButton cart;
    private javax.swing.JButton clothing;
    private javax.swing.JButton contact;
    private javax.swing.JButton electronic;
    private javax.swing.JButton feedback;
    private javax.swing.JButton footwear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
